name: Build and Cache Image
on:
  push:
    branches: [ master ]
jobs:
  cache-mybinder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BINDER_CACHE: true
          PUBLIC_REGISTRY_CHECK: true
          IMAGE_NAME: "cmelab/notebook-tutorials"
