name: Test PR and Image

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Image
        uses: jupyterhub/repo2docker-action@master
        with:
          LATEST_TAG_OFF: 'true'
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "cmelab/notebook-tutorials"
  
  test:
    runs-on: ubuntu-latest
    container: 
      image: cmelab/notebook-tutorials:${{ github.event.pull_request.head.sha }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: test notebooks
      shell: bash -l {0}
      run: python -m pytest -v --nbval-lax
