# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cache-mybinder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: 'true'
          MYBINDERORG_TAG: ${{ github.event.ref }}
          #DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          #DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          #IMAGE_NAME: "cmelab/notebook-tutorials"
      - name: comment on PR with Binder link
        uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var BRANCH_NAME = process.env.BRANCH_NAME;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${context.repo.owner}/${context.repo.repo}/${BRANCH_NAME}) :point_left: Launch a binder notebook on this branch`
            })
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}  
  
  test:
    #needs: [construct-container]
    runs-on: ubuntu-latest
    container: cmelab/notebook-tutorials

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: test notebooks
      shell: bash -l {0}
      run: python -m pytest -v --nbval-lax
