# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: setup miniconda
      uses: goanpeca/setup-miniconda@v1.6.0
      with:
        # https://github.com/goanpeca/setup-miniconda
        activate-environment: cme-notebook
        environment-file: environment.yml
        auto-activate-base: false
    
    - name: check env
      shell: bash -l {0}
      run: |
          conda info
          conda list
          which python
        
    - name: test notebooks
      shell: bash -l {0}
      run: |
          python -m pip install nbval pytest
          # skip opv sim until we have a working image with GAFF-foyer
          python -m pytest -v --nbval-lax radial-distribution-function.ipynb
          python -m pytest -v --nbval-lax MD_intro.ipynb
          python -m pytest -v --nbval-lax temperature-thermostat.ipynb

